# Generated by Django 5.1.3 on 2024-12-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
