# Generated by Django 5.1.3 on 2024-12-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=6)),
                ('assignee', models.CharField(max_length=255)),
                ('report_to', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TODO', 'To-Do'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='TODO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
