# Generated by Django 5.1.3 on 2024-12-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_task_options_task_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='report_to',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
