# Generated by Django 5.1.3 on 2024-12-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_task_assignee_alter_task_report_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='report_to',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
